export const en = {
  // Navigation
  'nav.signIn': 'Sign In',
  'nav.getStarted': 'Get Started',
  'nav.login': 'Login',
  'nav.start': 'Start',
  'nav.switchProfile': 'Switch Profile',
  'nav.switch': 'Switch',
  'nav.logout': 'Logout',

  // Landing Page
  'landing.hero.title': 'AI-Powered Learning',
  'landing.hero.subtitle': 'For Everyone, Everywhere',
  'landing.hero.description': 'Hagwon is a comprehensive educational platform designed for K-12 and GED students. With AI-powered lessons, multi-student support, and offline capabilities, we\'re making quality education accessible to learners around the world.',
  'landing.hero.startLearning': 'Start Learning Now',
  'landing.hero.multiStudent': 'Multi-Student Mode',
  'landing.hero.individualAccount': 'Individual Account',
  'landing.hero.availableWorldwide': 'Now Available Worldwide',

  // Features
  'features.title': 'Why Choose Hagwon?',
  'features.subtitle': 'Built specifically for diverse learning environments, from urban classrooms to rural communities',
  'features.aiPowered.title': 'AI-Powered Learning',
  'features.aiPowered.description': 'Personalized lessons generated by AI, adapted to each student\'s pace and learning style',
  'features.multiStudent.title': 'Multi-Student Support',
  'features.multiStudent.description': 'Perfect for shared computers - multiple students can use the same device with individual progress tracking',
  'features.offline.title': 'Offline-Friendly',
  'features.offline.description': 'Works even with limited internet connectivity, designed for rural and underserved areas',
  'features.adaptive.title': 'Adaptive Assessment',
  'features.adaptive.description': 'Smart diagnostic tests place students at the right level and track their progress',
  'features.global.title': 'Global Accessibility',
  'features.global.description': 'Designed for learners everywhere, from urban classrooms to remote villages',
  'features.k12.title': 'K-12 & GED Ready',
  'features.k12.description': 'Comprehensive curriculum from Kindergarten through Grade 12 plus GED preparation',

  // How It Works
  'howItWorks.title': 'How It Works',
  'howItWorks.subtitle': 'Get started in minutes with our simple, AI-powered learning process',
  'howItWorks.step1.title': 'Take Diagnostic Test',
  'howItWorks.step1.description': 'AI assesses your current knowledge level and places you at the right starting point',
  'howItWorks.step2.title': 'Learn & Practice',
  'howItWorks.step2.description': 'Work through personalized lessons with AI tutoring and interactive quizzes',
  'howItWorks.step3.title': 'Track Progress',
  'howItWorks.step3.description': 'Monitor your learning journey with detailed progress tracking and achievements',

  // Target Audience
  'audience.title': 'Perfect for Every Learning Environment',
  'audience.description': 'Whether you\'re in a bustling city school or a remote village classroom, Hagwon adapts to your unique learning environment and needs.',
  'audience.tryFree': 'Try It Free',
  'audience.homeschooling.title': 'Homeschooling',
  'audience.homeschooling.description': 'Complete curriculum with AI tutoring support for homeschooling families',
  'audience.rural.title': 'Rural Schools',
  'audience.rural.description': 'Offline-capable platform designed for areas with limited internet access',
  'audience.shared.title': 'Shared Devices',
  'audience.shared.description': 'Multiple students can use the same computer with individual progress tracking',
  'audience.selfPaced.title': 'Self-Paced',
  'audience.selfPaced.description': 'Learn at your own pace with AI that adapts to your learning speed',

  // Benefits
  'benefits.homeschooling': 'Perfect for homeschooling families',
  'benefits.rural': 'Ideal for rural schools with limited resources',
  'benefits.ged': 'Great for GED preparation',
  'benefits.shared': 'Works on shared computers',
  'benefits.offline': 'Offline learning capability',
  'benefits.selfPaced': 'Self-paced learning',

  // CTA
  'cta.title': 'Ready to Start Your Learning Journey?',
  'cta.description': 'Join thousands of learners worldwide who are already using Hagwon to achieve their educational goals.',

  // Footer
  'footer.tagline': 'AI-Powered Learning Platform for Everyone, Everywhere',
  'footer.copyright': '© 2024 Hagwon. Making quality education accessible worldwide.',

  // Themes
  'themes.title': 'Choose Theme',
  'themes.description': 'Theme changes apply instantly',
  'themes.done': 'Done',
  'themes.active': 'Active',

  // Profiles
  'profiles.title': 'Choose Your Profile',
  'profiles.description': 'Select your profile to continue learning',
  'profiles.createNew': 'Create New Profile',
  'profiles.enterPin': 'Enter 4-digit PIN',
  'profiles.createPin': 'Create a 4-digit PIN',
  'profiles.confirmPin': 'Confirm your PIN',
  'profiles.name': 'Profile Name',
  'profiles.selectAvatar': 'Select Avatar',
  'profiles.create': 'Create Profile',
  'profiles.cancel': 'Cancel',
  'profiles.delete': 'Delete Profile',

  // Language Selector
  'language.select': 'Select Language',
  'language.current': 'Current Language',
  'language.detected': 'Detected from your location',
  'language.browser': 'Detected from browser',
  'language.manual': 'Manually selected',

  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.tryAgain': 'Try Again',
  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.ok': 'OK',
  'common.yes': 'Yes',
  'common.no': 'No',
}